
GET http://localhost:3000/

###
GET http://localhost:3000/dsfsddsfds


# register route
### 
POST  http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "testsdafasdssas@example.com",
    "password": "1234"
}

# login route
### 
POST  http://localhost:3000/api/auth/login
Content-Type: application/json
Authorization: Bearar eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzM0N2MwZDEzMGU4NDg5MTdkZjRlODYiLCJpYXQiOjE2NjQ0NTE5NzEsImV4cCI6MTY2NDUzODM3MX0.AOgGy-3czZwEAZnCwg0zzhlwYwTlt_Kuiv69yWZgVIM


{
    "email": "testsdafasssas@example.com",      
    "password": "1234"
}


# refresh-token route
### 
POST  http://localhost:3000/api/auth/refresh-token
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzM0N2MwZDEzMGU4NDg5MTdkZjRlODYiLCJpYXQiOjE2NjQ0NTI2NjksImV4cCI6MTY5NjAxMDI2OX0.-RvQ4z2hasP0SDlp-UyrDxp6tOWPd2QV53cgCmTu1aQ"
}




# refresh-token route
### 
DELETE  http://localhost:3000/api/auth/logout
Content-Type: application/json


{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzM0N2MwZDEzMGU4NDg5MTdkZjRlODYiLCJpYXQiOjE2NjQ0NTM5NjEsImV4cCI6MTY5NjAxMTU2MX0.R5PO-bGpG2urSqWeeEEy06fDQufE9NtrT0u_zLU-WPw"
}
